[package]
name = "gpx_reader"
version = "0.0.1"
authors = [ "Andrii Dmytrenko <refresh.xss@gmail.com>" ]

[[bin]]
name = "gpx_reader"

[lib]
name = "gpx"
path = "src/lib.rs"

# [[lib]]
# name = "rb_gpx"
# path = "src/ruby_lib.rs"
